# Generated by Django 5.0.1 on 2025-11-04 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_updates', models.BooleanField(default=True, help_text='Receive emails when projects are updated')),
                ('ticket_comments', models.BooleanField(default=True, help_text='Receive emails when tickets receive comments')),
                ('ticket_status_changes', models.BooleanField(default=True, help_text='Receive emails when ticket status changes')),
                ('new_files', models.BooleanField(default=True, help_text='Receive emails when new files are uploaded')),
                ('weekly_summary', models.BooleanField(default=False, help_text='Receive weekly project summary emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
    ]
