web: gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 60 --log-file -
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py create_default_superuser
