# Generated by Django 5.0.1 on 2025-11-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        # Rename database tables from portfolio_* to company_*
        migrations.AlterModelTable(
            name='skill',
            table='company_skill',
        ),
        migrations.AlterModelTable(
            name='workexperience',
            table='company_workexperience',
        ),
        migrations.AlterModelTable(
            name='project',
            table='company_project',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='company_contactmessage',
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table='company_sitesettings',
        ),
        # Note: The many-to-many table company_project_technologies was already created
        # correctly in 0001_initial after we fixed the reference from portfolio.skill to company.skill
    ]
