# Generated by Django 5.0.1 on 2025-11-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_convert_imagefields_to_urlfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sitesettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skill',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workexperience',
            table=None,
        ),
    ]
